### PR TITLE
WIP: find a reasonable way to store the wave functions

### PR DESCRIPTION
**Pull request by JerryChen97**
Following @aaronszasz 's suggestion, and considering the fact that we can compute the entropy and correlation length directly from the wave function, I edited the code to store and return the wave function.

### CODE REVIEW

**Comment by JerryChen97** [comment]
In detail, since we create a new dmrg engine for each bond dimension `chi`, I furtherly separate each `chi` to simulate their own wave functions. 
Abstractly, there is a function like:
`run_atomic(Jx, Jy, Jz, chi, **args)`
for carrying the real dmrg process at the lowest level (from the perspective of treating TeNPy as a black box).

However, in practice, saving the wavefunctions seems quite cumbersome due to the high memory cost. In my own PC, it is usually stuck whenever I want to keep them in runtime; I believe this will cause the same problem even for the server. So now I am considering store them in the hard disk.

**Comment by aaronszasz** [comment]
Yes, I strongly recommend storing to hard disk.  Usually I only keep in memory the current wavefunction and the previous one.

**Comment by JerryChen97** [comment]
> Yes, I strongly recommend storing to hard disk. Usually I only keep in memory the current wavefunction and the previous one.

Cool. Do you have any suggestions on the file format? TeNPy3 seems to support a technique named `HDF5` but I haven't tried it yet.

**Comment by aaronszasz** [comment]
I don't have a particular recommendation.  In the past I've used pickle combined with gzip, but I think whatever TenPy has built in should be fine.  Your files will be really small anyway.

**Pull request merged**
