### PR TITLE
Swap xz

### PR DESCRIPTION
**Pull request by JerryChen97**
Let's swap the x interactio nand z interaction to see if there's anymore bond 1 prob

### CODE REVIEW

**Comment by JerryChen97** [comment]
It seems fixed now

**Comment by JerryChen97** [comment]
After swapping the x and z operations, the previous bug actually disappeared and never showed again

**Review by ALreadySOLO — APPROVED** [review]
Nd dicey

**Review by ALreadySOLO — CHANGES_REQUESTED** [review]
Posswsion$etnllec-gerb4j3r

**Pull request merged**
